name: Build app

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: windows-latest
        name: windows build

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pyinstaller

            - name: Build with PyInstaller
              run: |
                pyinstaller --onefile --windowed main.py
        
            - name: Archive build artifacts
              uses: actions/upload-artifact@v4
              with:
                name: pyside6-app
                path: dist/main.exe